# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.154.0/containers/alpine/.devcontainer/base.Dockerfile

# [Choice] Alpine version: 3.16, ..., 3.20
ARG VARIANT="alpine-3.20"

FROM mcr.microsoft.com/vscode/devcontainers/base:${VARIANT}

RUN apk update && \
    apk add --no-cache --virtual build-dependencies build-base git && \
    mkdir /usr/src && cd /usr/src && \
    git clone https://github.com/cc65/cc65.git && cd cc65 && \
    if [ "${CC65_VERSION}" != "latest" ]; then \
    git checkout tags/V${CC65_VERSION} -b "tag-${CC65_VERSION}"; \
    fi && \
    nice make -j2 && make install PREFIX=/usr prefix=/usr && \
    rm -rf /usr/src/cc65 && \
    apk del build-dependencies
